---
# tasks file for docker-registry
- name: login dockerhub
  docker_login:
    username: "hiba1512"
    password: "khadija123"
- name: push to dockerhub
  docker_image:
    name: appfront:latest
    repository: hiba1512/devops
    push: yes
    source: local
